<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
        $this->load->model('Member_model');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			if($this->session->userdata('username') == 'admin123'){
				$this->load->view('Home_admin');
			}
			else{
				$this->load->view('Home');
			}
			
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Login_form');
		}
		else
		{
			$username=$this->input->post('username'); //username=name form
			$password=$this->input->post('password');
			
			$cek_login_admin=$this->Admin_model->cek_login_admin($username,$password);
			$cek_login_member=$this->Member_model->cek_login_member($username,$password);


			if(!empty($cek_login_admin)){
				$this->session->set_userdata('logined',true);
				$this->session->set_userdata('username',$username);
				$this->load->view('Home_admin');
			}

			else if(!empty($cek_login_member)){
				$this->session->set_userdata('logined', true);
				$this->session->set_userdata('username',$username);
				$this->load->view('Home');

			}

			
			else 
			{
				$this->session->set_flashdata('gagal', "<div class=\"col-md-12\"><div class=\"alert alert-danger\" id=\"alert\">Username or Password is invalid</div></div>");
				redirect('Login');
			}
		}
        
    } 

    public function back(){
    	$this->load->view('Home');
    }

     public function back2(){
    	$this->load->view('Home_admin');
    }
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('username');

		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */